-- Connect to PDB and create microservice schema users
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER retail_user IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_user;
GRANT UNLIMITED TABLESPACE TO retail_user;

CREATE USER retail_product IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_product;
GRANT UNLIMITED TABLESPACE TO retail_product;

CREATE USER retail_order IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_order;
GRANT UNLIMITED TABLESPACE TO retail_order;

CREATE USER retail_cart IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_cart;
GRANT UNLIMITED TABLESPACE TO retail_cart;

CREATE USER retail_payment IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_payment;
GRANT UNLIMITED TABLESPACE TO retail_payment;

CREATE USER retail_inventory IDENTIFIED BY RetailPass123
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE SESSION TO retail_inventory;
GRANT UNLIMITED TABLESPACE TO retail_inventory;

COMMIT;
